# Iris 분류
- test 비율은 20%, random_state는 2021
- MinMaxScaler 적용
- cv=5
- 결정트리 - max_depth, min_samples_split
- 최적의 파라미터와 정확도 계산

### 데이터 전처리
- 데이터 불러오기

In [67]:
import pandas as pd 
import numpy as np 

In [46]:
from sklearn.datasets import load_iris
iris = load_iris()

In [47]:
# iris 데이터 (X)
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [48]:
# iris 결과 (y)
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [49]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

- 스케일링 (MinMaxScaler 적용)

In [101]:
from sklearn.preprocessing import MinMaxScaler

In [102]:
# 객체 생성
scaler = MinMaxScaler()

In [110]:
# 학습, 변환
iris_scaled = scaler.fit_transform(iris.data)

### train/test 데이터세트로 나누기

In [104]:
from sklearn.model_selection import train_test_split

In [105]:
X_train, X_test, y_train, y_test = train_test_split(
    iris_scaled, iris.target, test_size=0.2, random_state=2021, stratify=iris.target
#스케일링한 데이터
) 

In [106]:
X_train.shape , X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

## 모델링

### 학습 후 최적 모델 도출

In [107]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [120]:
params = {
    'max_depth' : [2,3,4],
    'min_samples_split' : [2,3]
}

In [121]:
dtc = DecisionTreeClassifier(random_state=2021) #객체생성
grid_dtc = GridSearchCV(dtc, param_grid=params, cv=5)

In [124]:
grid_dtc.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3, 4], 'min_samples_split': [2, 3]})

In [125]:
grid_dtc.best_score_

0.9666666666666668

In [126]:
grid_dtc.best_params_

{'max_depth': 4, 'min_samples_split': 2}

In [134]:
estimator = grid_dtc.best_estimator_

### 모델 평가

In [135]:
from sklearn.metrics import accuracy_score
pred = estimator.predict(X_test)
accuracy_score(y_test, pred)

0.9

### One - hot encoding 을 하는 경우

In [139]:
iris.target.shape

# sklearn 에서 데이터를 넣을땐 반드시 2차원으로 넣어야 한다!!

(150,)

In [138]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [143]:
iris.target.reshape(-1,1) #2차원으로 변환

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [144]:
classes = encoder.fit_transform(iris.target.reshape(-1,1))
classes.shape

(150, 3)

In [149]:
X_train, X_test, Y_train, Y_test = train_test_split(
    iris_scaled, classes, stratify=iris.target,
    test_size=0.2, random_state=2021
)

In [151]:
X_train.shape , X_test.shape, Y_train.shape, Y_test.shape

((120, 4), (30, 4), (120, 3), (30, 3))

In [152]:
Y_test[:5].toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [153]:
dtc = DecisionTreeClassifier(random_state=2021)

In [162]:
grid_dtc = GridSearchCV(dtc, param_grid=params, cv=5, scoring='accuracy')

In [163]:
grid_dtc.fit(X_train, Y_train.toarray())

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 3, 4], 'min_samples_split': [2, 3]},
             scoring='accuracy')

In [165]:
estimator = grid_dtc.best_estimator_
pred = grid_dtc.predict(X_test)

In [166]:
pred.shape

(30, 3)

In [168]:
accuracy_score(Y_test.toarray(), pred)

0.9